variables:
  DOCKER_DRIVER: overlay2
  TARGET_PLATFORM: linux/amd64,linux/arm64/v8,linux/arm/v7,linux/386
  FORCE_FULL_PIPELINE: 'false'
# Docker Hub
  DOCKERHUB_REPO_NAME: 'qemu'

stages:
  - test
  - prepare
  - build
  - publish

.default-rules:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success
    - if: $FORCE_FULL_PIPELINE == 'true'
      when: on_success
    - when: never

check-git-status:
  stage: test
  image: alpine:latest
  extends:
    - .default-rules
  script:
    - apk add wget jq gawk bash git
    - ./apply-templates.sh
    - if [ -n "$(git status --short)" ]; then echo "Templates not applied. Run './apply-templates.sh'. Exiting."; exit 1; fi

generate-pipelines:
  stage: prepare
  extends:
    - .default-rules
  image: python:alpine
  script:
    - pip install Jinja2
    - .scripts/generate-pipeline.py -p ${TARGET_PLATFORM} > generated-pipeline.yml
    - cat generated-pipeline.yml
  artifacts:
    paths:
      - generated-pipeline.yml
    expire_in: 5 mins

child-pipeline:
  stage: build
  extends:
    - .default-rules
  trigger:
    include:
      - artifact: generated-pipeline.yml
        job: generate-pipelines
    strategy: depend

dockerhub:readme:
  stage: publish
  variables:
    README_PATH: ${CI_PROJECT_DIR}/README.md
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $DOCKERHUB_REPO_NAME =~ /.+/ && $DOCKERHUB_PASSWORD =~ /.+/'
      when: on_success
    - when: never
  image:
    name: sheogorath/readme-to-dockerhub:latest
    entrypoint: ['']
  script:
    - node /app/index.js
