variables:
  DOCKER_DRIVER: overlay2
  TARGET_PLATFORM: linux/amd64,linux/arm64,linux/arm/v7
# Docker Hub
  DOCKERHUB_REPO_NAME: 'qemu'

stages:
  - test
  - prepare
  - build
  - publish

check-git-status:
  stage: test
  image: alpine:latest
  script:
    - apk add --no-cache wget jq gawk bash git
    - ./apply-templates.sh
    - if [ -n "$(git status --short)" ]; then echo "Templates not applied. Run './apply-templates.sh'. Exiting."; exit 1; fi

generate-pipelines:
  stage: prepare
  image: python:alpine
  script:
    - pip install --no-cache-dir Jinja2
    - .scripts/generate-pipeline.py -p ${TARGET_PLATFORM} > generated-pipeline.yml
    - cat generated-pipeline.yml
  artifacts:
    paths:
      - generated-pipeline.yml
    expire_in: 5 mins

child-pipeline:
  stage: build
  trigger:
    include:
      - artifact: generated-pipeline.yml
        job: generate-pipelines
    strategy: depend

dockerhub:readme:
  stage: publish
  variables:
    README_PATH: ${CI_PROJECT_DIR}/README.md
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master" && $DOCKERHUB_REPO_NAME =~ /.+/ && $DOCKERHUB_PASSWORD =~ /.+/'
      when: on_success
  image:
    name: sheogorath/readme-to-dockerhub:latest
    entrypoint: ['']
  script:
    - node /app/index.js
