#!/usr/bin/env bash

set -eux

export DEBIAN_FRONTEND="noninteractive"
export GNUPGHOME="$(mktemp -d)"

TARBALL="/$(basename ${QEMU_URL})"
SAVED_APT_MARK="$(apt-mark showmanual)"

apt-get update
apt-get install -y --no-install-recommends \
  ca-certificates \
  gnupg dirmngr \
  wget \
  xz-utils \
  apt-transport-https \
  software-properties-common \
  patch \

wget -O "${TARBALL}.sig" "${QEMU_URL}.sig"
wget -O "${TARBALL}" "${QEMU_URL}" --progress=dot:giga

for key in $QEMU_KEYS; do
  gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"
done

gpg --batch --verify "${TARBALL}.sig" "${TARBALL}"

gpgconf --kill all
rm -rf "${GNUPGHOME}"

mkdir -p /usr/src/qemu
cd /usr/src/qemu
tar -xf "${TARBALL}" -C . --strip-components=1
find /qemu-patches -name '*.patch' -type f -exec patch --strip 1 --input {} ';'

wget -q -O- 'https://download.ceph.com/keys/release.asc' | apt-key add -
echo "deb https://download.ceph.com/debian-octopus $(lsb_release -cs) main" >/etc/apt/sources.list.d/ceph.list

apt-get update
apt-get install -y --no-install-recommends \
  bzip2 \
  gcc \
  gnutls-dev \
  libaio-dev \
  libbz2-dev \
  libc-dev \
  libcap-dev \
  libcap-ng-dev \
  libcurl4-gnutls-dev \
  libglib2.0-dev \
  libiscsi-dev \
  libjpeg-dev \
  liblzo2-dev \
  libncursesw5-dev \
  libnfs-dev \
  libnuma-dev \
  libpixman-1-dev \
  libpng-dev \
  librbd-dev \
  libseccomp-dev \
  libspice-protocol-dev \
  libspice-server-dev \
  libssh-dev \
  libusb-1.0-0-dev \
  libusbredirparser-dev \
  make \
  pkg-config \
  python \
  tree \
  xfslibs-dev \
  zlib1g-dev

if echo "${QEMU_VERSION}" | grep -vE "^(4\.|5\.0\.).*"; then \
  export CONFIGURE_EXTRA_OPTIONS=" --enable-rng-none"
fi
./configure \
  --extra-cflags="-O2 -pipe -fomit-frame-pointer" \
  --target-list=" \
    i386-softmmu x86_64-softmmu aarch64-softmmu arm-softmmu \
    mips64-softmmu mips64el-softmmu ppc64-softmmu sparc64-softmmu \
  " \
  --disable-docs \
  --disable-git-update \
  --disable-gtk \
  --disable-pvrdma \
  --disable-qed \
  --disable-sdl \
  --disable-vte \
  --disable-xen \
  --enable-attr \
  --enable-bzip2 \
  --enable-cap-ng \
  --enable-curl \
  --enable-curses \
  --enable-fdt \
  --enable-gnutls \
  --enable-guest-agent \
  --enable-kvm \
  --enable-libiscsi \
  --enable-libnfs \
  --enable-libssh \
  --enable-libusb \
  --enable-linux-aio \
  --enable-linux-user \
  --enable-lzo \
  --enable-modules \
  --enable-numa \
  --enable-rbd \
  --enable-seccomp \
  --enable-spice \
  --enable-system \
  --enable-tools \
  --enable-usb-redir \
  --enable-vhost-net \
  --enable-vhost-user \
  --enable-vhost-vsock \
  --enable-virtfs \
  --enable-vnc \
  --enable-vnc-jpeg \
  --enable-vnc-png \
  --enable-xfsctl \
  ${CONFIGURE_EXTRA_OPTIONS:-}

make -j "$(nproc)"
make install

apt-mark auto '.*' > /dev/null
[ -z "$SAVED_APT_MARK" ] || apt-mark manual $SAVED_APT_MARK > /dev/null
find /usr/local \
  -type f \
  \( -executable -o -name '*.so' \) \
  -exec sh -c 'test "$(head -c 2 "$1")" != "#!"' sh '{}' ';' \
  -exec ldd '{}' ';' \
    | awk '/=>/ { print $(NF-1) }' \
    | sort -u \
    | xargs -r basename -a \
    | xargs -r dpkg-query --search \
    | cut -d: -f1 \
    | xargs -r apt-mark manual

apt-get install -y --no-install-recommends \
  ovmf \
  netcat
 
apt-get purge -y --auto-remove
rm -rf \
  /usr/src/qemu \
  ${TARBALL} \
  ${TARBALL}.sig \
  /qemu-patches \
  /var/lib/apt/lists/* \
  /tmp/* \
  /var/cache/* \
  /var/tmp/* \
  /var/log/*
 
# Basic test
qemu-img --version
